name: Test Backend Changes

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main  

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3


      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'


      - name: Install dependencies
        working-directory: backend
        run: npm install

      - name: Run tests
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        working-directory: backend
        run: npm test
